### ISSUE TITLE
Unable to remove palettes and make process diagram non-editable

### ISSUE THREAD

**Issue by protagonist51** [bpmn-io/bpmn-js-example-angular#10]
Hi,
I don't want to display palettes and I want to make the process diagram non-editable. How do I achieve this?

**Comment by pinussilvestrus** [comment]
Hi @protagonist51!

You just have to use the `Viewer` instead of  the `Modeler`. Inside the viewer, editing and the palette is disabled.  You will have a look inside the [diagram component](https://github.com/bpmn-io/bpmn-js-example-angular/blob/master/bpmn-js-app/src/app/diagram/diagram.component.ts#L20) of the example app and change it.

Furthermore, please have a look inside our [starter example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/starter) to learn more about getting along with our toolkit libraries. I'll close this  issue since no bug or feature request is described.

Note: Feel free to use [our forum](https://forum.bpmn.io/) to ask questions.
