### ISSUE TITLE
Publish import results with DiagramComponent

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-example-angular#5]
Use an [EventEmitter](https://angular.io/api/core/EventEmitter) with an [Output](https://angular.io/api/core/Output) to emit import results upstream.

__Tasks__

* [ ] expose import results via `importComplete` event (in both, error and success case)
* [ ] Rewrite test suite to verify for import results
* [ ] add failure test case, verifying import error

_Originally posted by @dankreiger in https://github.com/bpmn-io/bpmn-js-example-angular/pull/4#issuecomment-445573395_

**Comment by dankreiger** [comment]
@nikku I've attempted to address these points in my most recent commits, but there is still room for improvement - see https://github.com/bpmn-io/bpmn-js-example-angular/pull/4

It would be nice if there was something like Enzyme's `mount` to use in Jasmine so that we can easily test child components from the parent. Maybe there is something for this, but I haven't come across it yet.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js-example-angular/pull/7.
